customCommands:
  - key: '!'
    context: 'localBranches, remotes'
    command: 'git fetch --prune'
    description: 'Prune remote branches'
    prompts:
      - type: 'menu'
        title: 'Prune remote branches?'
        key: 'Confirm'
        options:
          - value: 'Confirm'
  - key: 'Æ'
    context: 'files'
    command: 'git add -A && git commit -m {{ .Form.CommitMessage | quote }}'
    description: 'Stage all files and commit with message'
    prompts:
      - type: 'input'
        key: 'CommitMessage'
        title: 'Stage all files and commit with message'
  - key: '^'
    context: 'global'
    command: 'git pull && git push'
    description: 'Push and pull'
    prompts:
      - type: 'menu'
        title: 'Push and pull?'
        key: 'Confirm'
        options:
          - value: 'Confirm'


gui:
  theme:
    activeBorderColor:
      - '#cd91ed'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#b7bdf8'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'

  authorColors:
    '*': '#b7bdf8'
